networks:
  internal:
services:
  webserver:
    container_name: 'f3com-backend'
    build:
      context: ./docker/bin/php
    restart: 'always'
    networks:
      - internal
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/html:rw
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "80:80"
    external_links:
      - webserver:f3com.localhost